### ISSUE TITLE
[Feature Request]: Building for ARM64 CPUs

### ISSUE THREAD

**Issue by shinyzhu** [infiniflow/infinity#1084]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

```Markdown
I'm using M2 MacBook with Docker Desktop.
But I cannot run Infinity in a docker instance because I cannot pull x86_64 images.
It would be better for providing ARM64 built images.

I'm aware that Rosetta would be a solution but I don't have Rosetta on my Mac.

On the other hand.
There are servers running with ARM CPUs I'd like to deploy Infinity to.
```

### Describe the feature you'd like

Publish docker images for ARM64.

### Additional information

I tried to build from source on an `arm64v8/ubuntu:23.10` image but got many errors like:

- `simde` missing. (fixed with `apt-get install libsimde-dev`)
- failed with `-msse4.2` and `-mfma`

**Comment by yingfeng** [comment]
Fix by #2082

**Comment by shinyzhu** [comment]
Well done.

Thanks a lot.

**Comment by jc7ctzphbf-dotcom** [comment]
@shinyzhu can you share you dockerfile for aarch64 or share you docker images, I can't build it

**Comment by jatinsethi98** [comment]
if you found this issue by search, this might help. i built a native `arm64-apple-darwin` port of Infinity 0.7.3 in a fork. it's my own work, not affiliated with InfiniFlow. builds and runs on macOS with no Docker and no Rosetta.

while i was in there i tuned the HNSW index build for the M-series memory system. prefetch changes, a 128-byte stride, a four-accumulator L2 kernel, runtime dispatch. on SIFT1M on an M4 it builds in 35.3s. FAISS 1.15 linked to Accelerate takes 58.1s at the same recall@10.

scope, so nobody gets surprised. engine core, server lifecycle and HNSW path run natively. full-text, update/delete, bulk import and crash recovery are not verified on macOS. i haven't retested Linux since the port.

https://github.com/jatinsethi98/infinity-apple-silicon

bug reports welcome. if maintainers want any of this upstream, happy to do the work.
