### ISSUE TITLE
[Bug]: Docker Container keep crashing whenever started

### ISSUE THREAD

**Issue by EricLiuAno** [infiniflow/infinity#788]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

b967513

### Other environment information

```Markdown
Ubuntu 20.04.1 LTS
Docker 20.10.11
```

### Actual behavior

I had pulled older version of the image in Feb and tried using the database. Currently, to update the image, I've pulled the latest docker image and started the container with docker run, but the container just keep exiting with error code 139. 

docker logs shows the following message

### Steps to reproduce

```Markdown
Just run a container with the latest image.
```

### Additional information

![image](https://github.com/infiniflow/infinity/assets/61333545/b4fafd8a-abd7-40cb-b22a-907b426a54ae)
Don't know if these helps solving the problem.
Please mention if any other info is needed.

**Comment by JinHai-CN** [comment]
Compared to the February version, the metadata structure of the current version has been updated, which means that the Docker of the current version may encounter errors when reading the metadata of the previous commit. You can delete all the data in the database directory and restart the new version of the program. Or, you can still use an older version of Docker so that you can read the current data.

The default data directory is:/tmp/infinity, but it should be noted that deleting its contents will result in the loss of previously imported data.

**Comment by JinHai-CN** [comment]
Fixed in latest version and if the problem raise again, please reopen the issue.
